# Generated by Django 5.1 on 2024-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('monday', models.CharField(max_length=900, null=True)),
                ('tuesday', models.CharField(max_length=900, null=True)),
                ('wednesday', models.CharField(max_length=900, null=True)),
                ('thursday', models.CharField(max_length=900, null=True)),
                ('friday', models.CharField(max_length=900, null=True)),
            ],
        ),
    ]
