# Generated by Django 5.1 on 2024-09-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friday_calories',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='monday_calories',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='thursday_calories',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tuesday_calories',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wednesday_calories',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
