# Generated by Django 5.1 on 2024-09-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_person_friday_calories_person_monday_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='friday_calories',
        ),
        migrations.RemoveField(
            model_name='person',
            name='monday_calories',
        ),
        migrations.RemoveField(
            model_name='person',
            name='thursday_calories',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tuesday_calories',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wednesday_calories',
        ),
        migrations.AddField(
            model_name='person',
            name='carbohydrates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cholesterol',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='fiber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='potassium',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sodium',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sugar',
            field=models.IntegerField(null=True),
        ),
    ]
